#!/usr/bin/python
# EASY-INSTALL-SCRIPT: 'plugwiselib==0.2dev','plugwise_util'
__requires__ = 'plugwiselib==0.2dev'
import pkg_resources
pkg_resources.run_script('plugwiselib==0.2dev', 'plugwise_util')
